// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnaPMzVm82G2lDf9je9PiUiIfc9dfBRxY',
    appId: '1:507100286034:web:88fb7601e2285747c4e38b',
    messagingSenderId: '507100286034',
    projectId: 'winter-page',
    authDomain: 'winter-page.firebaseapp.com',
    storageBucket: 'winter-page.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxvV_sDci0GZDx2KRJnmqGrjzyoUQCB58',
    appId: '1:507100286034:android:bf3d5f2485b5051fc4e38b',
    messagingSenderId: '507100286034',
    projectId: 'winter-page',
    storageBucket: 'winter-page.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2lYPbo7PMkaoMsKPvxMzUpUSMu8ziIZ8',
    appId: '1:507100286034:ios:f6be1eca23a1b532c4e38b',
    messagingSenderId: '507100286034',
    projectId: 'winter-page',
    storageBucket: 'winter-page.firebasestorage.app',
    iosBundleId: 'com.example.winter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2lYPbo7PMkaoMsKPvxMzUpUSMu8ziIZ8',
    appId: '1:507100286034:ios:f6be1eca23a1b532c4e38b',
    messagingSenderId: '507100286034',
    projectId: 'winter-page',
    storageBucket: 'winter-page.firebasestorage.app',
    iosBundleId: 'com.example.winter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnaPMzVm82G2lDf9je9PiUiIfc9dfBRxY',
    appId: '1:507100286034:web:a4996717fc6f520cc4e38b',
    messagingSenderId: '507100286034',
    projectId: 'winter-page',
    authDomain: 'winter-page.firebaseapp.com',
    storageBucket: 'winter-page.firebasestorage.app',
  );
}
